name: Build CapsLang
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Build Solution
        run: |
          msbuild.exe ./src/netframework/CapsLang.sln /p:platform="Any CPU" /p:configuration="Release"
      
      - name: Upload Setup Artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: CapsLang_Setup
          path: src\netframework\CapsLang.Setup\Release\

      - name: Upload Binaries Artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: CapsLang_Binaries
          path: src\netframework\CapsLang.Tray\bin\Release\
