name: Build CapsLang
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        
      - name: Navigate to folder
        run: cd $GITHUB_WORKSPACE
        
      - name: Restore Packages
        run: nuget restore CapsLang.sln

      - name: Build Solution
        run: |
          msbuild.exe CapsLang.sln /p:platform="Any CPU" /p:configuration="Release"
