name: Build CapsLang
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Build Solution
        run: |
          msbuild.exe ./src/netframework/CapsLang.sln /p:platform="Any CPU" /p:configuration="Release"
